### ISSUE TITLE
Allow pyperformance to compile CPython with the JIT enabled.

### ISSUE THREAD

**Issue by diegorusso** [python/pyperformance#345]
From 3.13, CPython can be built with the JIT and it doesn't seem to be the way to pass custom flags to the configure or the compile step: https://github.com/python/pyperformance/blob/784d0421f387f6245ecbbe744a530c238c60c741/pyperformance/compile.py#L277

It would be nice to have either:
* a way to pass custom flags to the configure via CLI/benchmark.conf
* hard code the jit (like lto/pgo) in the benchmark.conf

I don't have strong opinions for both implementations and TBH we could have both. The former is more generic and flexible, the latter more explicit.

**Comment by brandtbucher** [comment]
@mdboom, would this be helpful for us?

**Comment by mdboom** [comment]
I think it's a good idea in order to make it easier for others.  The Faster CPython team's [infrastructure](https://github.com/faster-cpython/benchmarking-public) doesn't actually use `pyperformance compile`, but in the interests of open source, it probably wouldn't be a bad idea to close the gap there so `pyperformance compile` is feature-complete and our infrastructure could start using it.

**Comment by diegorusso** [comment]
Thanks for confirming that. I guess the only way possible for now is to compile Python outside of pyperformance and then instruct pyperformance to run benchmarks with the just compiled CPython.
I agree with @mdboom, I think it is useful if we can expose both the JIT (and maybe the free threading) as configuration options.
For the sake of flexibility it would be nice to expose an interface to pass whatever flags we want to the `./configure`.

**Comment by diegorusso** [comment]
PR: https://github.com/python/pyperformance/pull/351
